In [34]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [35]:
tf.__version__

'2.3.0'

In [36]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [37]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [38]:
x = dataset.iloc[: , 3:-1].values
k = dataset.iloc[: , 3:-1].values
y = dataset.iloc[:, -1].values
z = np.array([[600, 'France', 'Male' , 40, 3, 60000, 2, 1, 1, 50000]])

In [39]:
print(k[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [40]:
print(y)

[1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0
 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0
 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 0 1 0 0 0 0 0 

# Encoding of Gender

In [41]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [42]:
print(x[:, 2])

[0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 1 0 0 1 0 1 1 1 0 1 0 1 1 0 0 0 1
 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 0 0 1 1 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1
 1 1 1 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 0 0 1
 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0
 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1
 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 1 1 1 0 0
 1 1 0 0 0 1 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1 1 0 1 0 1 1
 0 0 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1 0 1
 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0
 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1
 1 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1
 0 1 1 1 0 1 1 1 0 1 0 0 

# **Encoding of Geography**

In [43]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y , test_size = 0.2, random_state = 0)

In [45]:
# Scaling is COMPULSORY for Neural Network

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [47]:
print(x_train[0 , :])

[-1.01460667 -0.5698444   1.74309049  0.16958176 -1.09168714 -0.46460796
  0.00666099 -1.21571749  0.8095029   0.64259497 -1.03227043  1.10643166]


In [48]:
ann = tf.keras.models.Sequential()
# Hidden Layer 1
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))
# Hidden Layer 2
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))
# Output Layer
ann.add(tf.keras.layers.Dense(units = 1, activation='sigmoid'))

In [49]:
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics =['accuracy'])

In [50]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 938us/step - loss: 0.7351 - accuracy: 0.5701
Epoch 2/100
250/250 [==============================] - 0s 917us/step - loss: 0.5327 - accuracy: 0.7918
Epoch 3/100
250/250 [==============================] - 0s 901us/step - loss: 0.4830 - accuracy: 0.7976
Epoch 4/100
250/250 [==============================] - 0s 952us/step - loss: 0.4560 - accuracy: 0.7994
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4389 - accuracy: 0.8098
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4283 - accuracy: 0.8173
Epoch 7/100
250/250 [==============================] - 0s 946us/step - loss: 0.4211 - accuracy: 0.8216
Epoch 8/100
250/250 [==============================] - 0s 887us/step - loss: 0.4157 - accuracy: 0.8229
Epoch 9/100
250/250 [==============================] - 0s 931us/step - loss: 0.4113 - accuracy: 0.8240
Epoch 10/100
250/250 [==============================] - 0s 887us/step - loss:

In [51]:
#y_pred = ann.predict(sc.transform())
z[:,2] = le.transform(z[:,2])


In [52]:
z[:,2]

array(['1'], dtype='<U21')

In [53]:
z = np.array(ct.transform(z))

In [54]:
z

array([['1.0', '0.0', '0.0', '600', '1', '40', '3', '60000', '2', '1',
        '1', '50000']], dtype='<U32')

In [55]:
z = sc.transform(z)

In [56]:
z

array([[ 0.98560362, -0.5698444 , -0.57369368, -0.52111599,  0.91601335,
         0.10961719, -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,
         0.9687384 , -0.87203322]])

In [57]:
y_pred = ann.predict(z)

In [58]:
y_pred

array([[0.04353419]], dtype=float32)

In [59]:
y_x_test_pred = ann.predict(x_test)

In [60]:
print(y_x_test_pred[0])

[0.32201058]


In [61]:
for i in range(len(y_x_test_pred)):
  if(y_x_test_pred[i] > 0.5):
    y_x_test_pred[i] = 1
  else:
    y_x_test_pred[i] = 0

In [62]:
np.set_printoptions(threshold=np.inf)
y_x_test_pred

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_x_test_pred)

In [64]:
cm

array([[1509,   86],
       [ 198,  207]])

In [65]:
accuracy_score(y_test, y_x_test_pred)

0.858

In [66]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

[[0.04353419]]
